### ISSUE TITLE
"Cut" a release based on the Git tag, for easier comparison

### ISSUE THREAD

**Issue by smbambling** [rpki-client/rpki-client-portable#60]
Would it be possible to also cut a release based on each version that is tagged?

This would allow for easier comparison between version and also also tooling to compare versions more easily via the GitHub api.

**Comment by cjeker** [comment]
There release tarballs are the official releases. Because of the way release tarballs are made they are not comparable to anything on github. Because of this we only tag but we do not provide anything from github.
This github repo is just our way to make it transparent on how -portable is made.
The release tarballs are signed and the real thing.

**Comment by smbambling** [comment]
Understood, that the tarballs are not created via GitHub. 

Is it still possible to create a release without adding artifacts, this allows easier querying via the GitHub API. The main being able to easily list the 'latest' release. This is not easily possible with only tags

**Comment by cjeker** [comment]
@sebastianbenoit and @job should we upload the release tar.gz into github and make them offical releases?
It is an extra step and I have not tried out how well it works (it seems you can attach them to a tag).

**Comment by smbambling** [comment]
No real worries on this my current work around is to query the [Dockerfile](https://github.com/rpki-client/rpki-client-container/blob/master/Dockerfile#L34) for the ARG Version from the rpki-client-container repository. This mostly gives me the 'latest' release version.

**Comment by smbambling** [comment]
That unfortunately requires the repository to be checked out which puts a lot of unneeded overhead to just obtain the latest release version.

**Comment by sebastianbenoit** [comment]
> @sebastianbenoit and @job should we upload the release tar.gz into github and make them offical releases? It is an extra step and I have not tried out how well it works (it seems you can attach them to a tag).

a fellow committer has similar problems ;)
https://github.com/pgRouting/pgrouting/issues/1013

Then there is this description of how to add signatures:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases
(my believe was that that was not working because the tarballs generated by github on the fly were not stable?)

I have done this by just uploading our files:
https://github.com/rpki-client/rpki-client-portable/releases/tag/7.8
github adds the "Source Code" files.

**Comment by cjeker** [comment]
Yes, my main problem is with the "Source Code" files which are actually not what we want to release.
People should not use this github repo for official builds, most of the code is sourced from a 2nd github repo that is recreated daily and if you're not careful you build something completely different to the official release.
Especially now that we switched away from the OpenBSD stable branches.

**Comment by cjeker** [comment]
OK. We'll try to add a github release in the future. I added releases for some of the historic releases as well.
